// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB2QRAPqgiyRz1TabACLlEjZNWN2105X7w',
//     appId: '1:568492421002:web:cca7b65eda4026604aa273',
//     messagingSenderId: '568492421002',
//     projectId: 'wwf-api',
//     authDomain: 'wwf-api.firebaseapp.com',
//     storageBucket: 'wwf-api.appspot.com',
//     measurementId: 'G-K706PZN3VH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDj0U4rgeyCqhIBxhZ_2jhsPfFqw1CaiCU',
//     appId: '1:568492421002:android:05267fc9add6e5c94aa273',
//     messagingSenderId: '568492421002',
//     projectId: 'wwf-api',
//     storageBucket: 'wwf-api.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAE4DxxI5UNQav44Lw1iSIYsPqYz9pWmg8',
//     appId: '1:568492421002:ios:e1d47ebbb19458c34aa273',
//     messagingSenderId: '568492421002',
//     projectId: 'wwf-api',
//     storageBucket: 'wwf-api.appspot.com',
//     iosClientId:
//         '568492421002-2gi0pd81s7s1fdok1co60sg1t35uc8jl.apps.googleusercontent.com',
//     iosBundleId: 'com.wwf.learning',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAE4DxxI5UNQav44Lw1iSIYsPqYz9pWmg8',
//     appId: '1:568492421002:ios:e1d47ebbb19458c34aa273',
//     messagingSenderId: '568492421002',
//     projectId: 'wwf-api',
//     storageBucket: 'wwf-api.appspot.com',
//     iosClientId:
//         '568492421002-2gi0pd81s7s1fdok1co60sg1t35uc8jl.apps.googleusercontent.com',
//     iosBundleId: 'com.wwf.learning',
//   );
// }
